export default [
    {
        id: 1,
        img: "/images/cat1.jpeg",
        name: "Salém",
        city: "Itajubá, MG",
        animal: "Gato",
        size: "Porte pequeno",
    },
    {
        id: 2,
        img: "/images/dog1.jpeg",
        name: "Farofa",
        city: "Itajubá, MG",
        animal: "Cachorro",
        size: "Porte grande",
    },
    {
        id: 3,
        img: "/images/cat2.jpeg",
        name: "Mingau",
        city: "Itajubá, MG",
        animal: "Gato",
        size: "Porte pequeno",
    },
    {
        id: 4,
        img: "/images/dog2.jpeg",
        name: "Zeus",
        city: "Itajubá, MG",
        animal: "Cachorro",
        size: "Porte médio",
    },
    {
        id: 5,
        img: "/images/dog3.jpeg",
        name: "Aurélio",
        city: "Itajubá, MG",
        animal: "Cachorro",
        size: "Porte pequeno",
    },    
    {
        id: 6,
        img: "/images/dog4.jpeg",
        name: "Abílio",
        city: "Itajubá, MG",
        animal: "Cachorro",
        size: "Porte pequeno",
    }, 
]